# Generated by Django 6.0.5 on 2026-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OFWRegistration',
            fields=[
                ('client_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('worker_type', models.CharField(choices=[('Land-based', 'Land-based OFW'), ('Sea-based', 'Sea-based OFW (Seafarer)')], max_length=20)),
                ('country_of_deployment', models.CharField(choices=[('Saudi Arabia', 'Saudi Arabia'), ('UAE', 'United Arab Emirates'), ('Hong Kong', 'Hong Kong'), ('Singapore', 'Singapore'), ('Qatar', 'Qatar'), ('International Waters', 'International Waters (Sea-based)'), ('Others', 'Others')], max_length=50)),
                ('occupation_position', models.CharField(max_length=100)),
                ('recruitment_agency', models.CharField(max_length=150)),
                ('owwa_membership_status', models.CharField(choices=[('Active', 'Active Member'), ('Expired', 'Expired'), ('Not a Member', 'Not a Member')], max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Child', 'Child'), ('Others', 'Others')], max_length=20)),
                ('emergency_contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OWWAOfficerProfile',
            fields=[
                ('client_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role_position', models.CharField(choices=[('Regional Director', 'Regional Director'), ('Welfare Officer', 'Welfare Officer'), ('Case Officer', 'Case Officer'), ('Admin Staff', 'Admin Staff'), ('Legal Officer', 'Legal Officer')], max_length=35)),
                ('specialty_focus_area', models.CharField(choices=[('Repatriation', 'Repatriation Services'), ('Legal Assistance', 'Legal Assistance'), ('Crisis Response', 'Crisis Response'), ('Medical Assistance', 'Medical Assistance'), ('Administration', 'Administration'), ('Documentation', 'Documentation')], max_length=35)),
                ('assigned_region', models.CharField(default='Region V (Bicol Region)', max_length=50)),
                ('assigned_province', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_city', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('Permanent', 'Permanent'), ('Contractual', 'Contractual'), ('Probationary', 'Probationary')], max_length=20)),
                ('office_address', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
