# Generated by Django 6.0 on 2026-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofwregistration',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
