# Generated by Django 6.0 on 2026-05-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0002_ofwregistration_first_name_ofwregistration_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Change History',
                'verbose_name_plural': 'Password Change History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=30)),
                ('department', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('current_password', models.CharField(default='', max_length=255)),
                ('new_password_hash', models.CharField(default='', max_length=255)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('session_timeout', models.CharField(default='30', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('new_clients', models.BooleanField(default=True)),
                ('program_updates', models.BooleanField(default=True)),
                ('system_maintenance', models.BooleanField(default=False)),
                ('emergency_requests', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('monthly_reports', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fil', 'Filipino'), ('ceb', 'Cebuano'), ('ilo', 'Ilocano')], default='en', max_length=10)),
                ('timezone', models.CharField(choices=[('Asia/Manila', 'Asia/Manila (GMT+8)'), ('Asia/Tokyo', 'Asia/Tokyo (GMT+9)'), ('Asia/Singapore', 'Asia/Singapore (GMT+8)')], default='Asia/Manila', max_length=40)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('default_dashboard', models.CharField(default='overview', max_length=50)),
                ('allow_analytics', models.BooleanField(default=True)),
                ('share_for_research', models.BooleanField(default=False)),
                ('enable_session_logging', models.BooleanField(default=True)),
                ('data_retention', models.CharField(choices=[('1-year', '1 Year'), ('2-years', '2 Years'), ('5-years', '5 Years'), ('indefinite', 'Indefinitely')], default='2-years', max_length=20)),
                ('show_activity_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
