# Generated by Django 6.0 on 2026-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0003_passwordchangehistory_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owwaofficerprofile',
            name='assigned_city',
            field=models.CharField(blank=True, choices=[('manila', 'Manila'), ('quezon-city', 'Quezon City'), ('caloocan', 'Caloocan'), ('pasay', 'Pasay'), ('makati', 'Makati'), ('pasig', 'Pasig'), ('taguig', 'Taguig'), ('paranaque', 'Parañaque'), ('las-piñas', 'Las Piñas'), ('muntilupa', 'Muntinlupa'), ('marikina', 'Marikina'), ('san-juan', 'San Juan'), ('mandaluyong', 'Mandaluyong'), ('valenzuela', 'Valenzuela'), ('navotas', 'Navotas'), ('malabon', 'Malabon'), ('cebu-city', 'Cebu City'), ('lapu-lapu-city', 'Lapu-Lapu City'), ('mandaue', 'Mandaue'), ('davao-city', 'Davao City'), ('zamboanga-city', 'Zamboanga City'), ('cagayan-de-oro', 'Cagayan de Oro'), ('bacolod', 'Bacolod'), ('iloilo-city', 'Iloilo City')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owwaofficerprofile',
            name='assigned_province',
            field=models.CharField(blank=True, choices=[('ilocos-norte', 'Ilocos Norte'), ('ilocos-sur', 'Ilocos Sur'), ('la-union', 'La Union'), ('pangasinan', 'Pangasinan'), ('batanes', 'Batanes'), ('cagayan', 'Cagayan'), ('isabela', 'Isabela'), ('nueva-vizcaya', 'Nueva Vizcaya'), ('quirino', 'Quirino'), ('bataan', 'Bataan'), ('bulacan', 'Bulacan'), ('nueva-ecija', 'Nueva Ecija'), ('pampanga', 'Pampanga'), ('tarlac', 'Tarlac'), ('zambales', 'Zambales'), ('aurora', 'Aurora'), ('batangas', 'Batangas'), ('cavite', 'Cavite'), ('laguna', 'Laguna'), ('rizal', 'Rizal'), ('quezon', 'Quezon'), ('marinduque', 'Marinduque'), ('occidental-mindoro', 'Occidental Mindoro'), ('oriental-mindoro', 'Oriental Mindoro'), ('palawan', 'Palawan'), ('romblon', 'Romblon'), ('albay', 'Albay'), ('camarines-norte', 'Camarines Norte'), ('camarines-sur', 'Camarines Sur'), ('catanduanes', 'Catanduanes'), ('masbate', 'Masbate'), ('sorsogon', 'Sorsogon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='owwaofficerprofile',
            name='assigned_region',
            field=models.CharField(choices=[('region-1', 'Region I (Ilocos Region)'), ('region-2', 'Region II (Cagayan Valley)'), ('region-3', 'Region III (Central Luzon)'), ('region-4a', 'Region IV-A (CALABARZON)'), ('region-4b', 'Region IV-B (MIMAROPA)'), ('region-5', 'Region V (Bicol Region)'), ('region-6', 'Region VI (Western Visayas)'), ('region-7', 'Region VII (Central Visayas)'), ('region-8', 'Region VIII (Eastern Visayas)'), ('region-9', 'Region IX (Zamboanga Peninsula)'), ('region-10', 'Region X (Northern Mindanao)'), ('region-11', 'Region XI (Davao Region)'), ('region-12', 'Region XII (SOCCSKSARGEN)'), ('region-13', 'Region XIII (Caraga)'), ('car', 'Cordillera Administrative Region (CAR)'), ('ncr', 'National Capital Region (NCR)'), ('barmm', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)')], default='region-5', max_length=20),
        ),
    ]
