# Generated by Django 6.0 on 2026-05-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0004_alter_owwaofficerprofile_assigned_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofwregistration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='nationality',
            field=models.CharField(default='Filipino', max_length=50),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ofwregistration',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
