# Generated by Django 6.0 on 2026-05-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0005_ofwregistration_address_ofwregistration_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='nationality',
            field=models.CharField(choices=[('Filipino', 'Filipino'), ('American', 'American'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Indian', 'Indian'), ('Other', 'Other')], default='Filipino', max_length=20),
        ),
    ]
