# Generated by Django 6.0 on 2026-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0006_alter_ofwregistration_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='address',
            field=models.CharField(blank=True, choices=[('123 Rizal Street, Brgy. San Jose, Quezon City, Metro Manila', '123 Rizal Street, Brgy. San Jose, Quezon City, Metro Manila'), ('456 Bonifacio Avenue, Brgy. San Roque, Makati City, Metro Manila', '456 Bonifacio Avenue, Brgy. San Roque, Makati City, Metro Manila'), ('789 España Boulevard, Brgy. Santa Cruz, Manila, Metro Manila', '789 España Boulevard, Brgy. Santa Cruz, Manila, Metro Manila'), ('101 Marcos Highway, Brgy. Mayamot, Antipolo City, Rizal', '101 Marcos Highway, Brgy. Mayamot, Antipolo City, Rizal'), ('202 Gov. Alvarez Avenue, Brgy. San Rafael, Pasig City, Metro Manila', '202 Gov. Alvarez Avenue, Brgy. San Rafael, Pasig City, Metro Manila'), ('303 Quezon Avenue, Brgy. Sto. Nino, Quezon City, Metro Manila', '303 Quezon Avenue, Brgy. Sto. Nino, Quezon City, Metro Manila'), ('404 Taft Avenue, Brgy. San Rafael, Pasay City, Metro Manila', '404 Taft Avenue, Brgy. San Rafael, Pasay City, Metro Manila'), ('505 Roxas Boulevard, Brgy. San Isidro, Parañaque City, Metro Manila', '505 Roxas Boulevard, Brgy. San Isidro, Parañaque City, Metro Manila'), ('606 EDSA, Brgy. Ugong, Pasig City, Metro Manila', '606 EDSA, Brgy. Ugong, Pasig City, Metro Manila'), ('707 C-5 Road, Brgy. Pinagbuhatan, Pasig City, Metro Manila', '707 C-5 Road, Brgy. Pinagbuhatan, Pasig City, Metro Manila')], max_length=1000),
        ),
    ]
