# Generated by Django 6.0 on 2026-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0007_alter_ofwregistration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='address',
            field=models.CharField(blank=True, choices=[('Purok 3, San Roque, Pili, Camarines Sur', 'Purok 3, San Roque, Pili, Camarines Sur'), ('Zone 4, San Francisco, Ocampo, Camarines Sur', 'Zone 4, San Francisco, Ocampo, Camarines Sur'), ('Sitio Iyam, San Jose, Camarines Sur', 'Sitio Iyam, San Jose, Camarines Sur'), ('Del Rosario, Naga City, Camarines Sur', 'Del Rosario, Naga City, Camarines Sur'), ('San Felipe, Naga City, Camarines Sur', 'San Felipe, Naga City, Camarines Sur'), ('Peñafrancia Avenue, Naga City, Camarines Sur', 'Peñafrancia Avenue, Naga City, Camarines Sur'), ('Jose Abad Santos Drive, Naga City, Camarines Sur', 'Jose Abad Santos Drive, Naga City, Camarines Sur'), ('San Isidro, Iriga City, Camarines Sur', 'San Isidro, Iriga City, Camarines Sur'), ('Sagrada Familia, Baao, Camarines Sur', 'Sagrada Familia, Baao, Camarines Sur'), ('Sto. Domingo, Bato, Camarines Sur', 'Sto. Domingo, Bato, Camarines Sur'), ('Legazpi Port District, Legazpi City, Albay', 'Legazpi Port District, Legazpi City, Albay'), ('Old Albay District, Daraga, Albay', 'Old Albay District, Daraga, Albay'), ('Poblacion, Sorsogon City, Sorsogon', 'Poblacion, Sorsogon City, Sorsogon'), ('Catburawan, Masbate City, Masbate', 'Catburawan, Masbate City, Masbate'), ('Tabaco, Tabaco City, Albay', 'Tabaco, Tabaco City, Albay'), ('Magsaysay Avenue, Baguio City, Benguet', 'Magsaysay Avenue, Baguio City, Benguet'), ('Osmeña Boulevard, Cebu City, Cebu', 'Osmeña Boulevard, Cebu City, Cebu'), ('J.P. Laurel Avenue, Davao City, Davao del Sur', 'J.P. Laurel Avenue, Davao City, Davao del Sur'), ('General Luna Street, Iloilo City, Iloilo', 'General Luna Street, Iloilo City, Iloilo')], max_length=200),
        ),
    ]
