# Generated by Django 6.0 on 2026-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0008_alter_ofwregistration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='address',
            field=models.CharField(blank=True, choices=[('123 San Miguel Street, San Vicente Poblacion, Calabanga, Camarines Sur', '123 San Miguel Street, San Vicente Poblacion, Calabanga, Camarines Sur'), ('456 Rizal Street, San Francisco, Calabanga, Camarines Sur', '456 Rizal Street, San Francisco, Calabanga, Camarines Sur'), ('789 Bonifacio Avenue, San Pedro, Calabanga, Camarines Sur', '789 Bonifacio Avenue, San Pedro, Calabanga, Camarines Sur'), ('321 Quezon Avenue, San Isidro, Calabanga, Camarines Sur', '321 Quezon Avenue, San Isidro, Calabanga, Camarines Sur'), ('654 Magsaysay Street, Sta. Cruz, Calabanga, Camarines Sur', '654 Magsaysay Street, Sta. Cruz, Calabanga, Camarines Sur'), ('987 Del Pilar Road, San Pablo, Calabanga, Camarines Sur', '987 Del Pilar Road, San Pablo, Calabanga, Camarines Sur'), ('147 Lopez Jaena Street, Taculod, Calabanga, Camarines Sur', '147 Lopez Jaena Street, Taculod, Calabanga, Camarines Sur'), ('258 Aquino Drive, San Antonio, Calabanga, Camarines Sur', '258 Aquino Drive, San Antonio, Calabanga, Camarines Sur'), ('369 Hizon Avenue, San Juan, Calabanga, Camarines Sur', '369 Hizon Avenue, San Juan, Calabanga, Camarines Sur'), ('741 Rizal Boulevard, Binanuahan, Calabanga, Camarines Sur', '741 Rizal Boulevard, Binanuahan, Calabanga, Camarines Sur'), ('Legazpi Port District, Legazpi City, Albay', 'Legazpi Port District, Legazpi City, Albay'), ('Poblacion, Sorsogon City, Sorsogon', 'Poblacion, Sorsogon City, Sorsogon'), ('Osmeña Boulevard, Cebu City, Cebu', 'Osmeña Boulevard, Cebu City, Cebu'), ('J.P. Laurel Avenue, Davao City, Davao del Sur', 'J.P. Laurel Avenue, Davao City, Davao del Sur')], max_length=200),
        ),
    ]
