# Generated by Django 6.0 on 2026-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0009_alter_ofwregistration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
