# Generated by Django 6.0 on 2026-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0010_alter_ofwregistration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='owwaofficerprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
