# Generated by Django 6.0 on 2026-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0011_owwaofficerprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owwaofficerprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='owwaofficerprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='owwaofficerprofile',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
