# Generated by Django 6.0.5 on 2026-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0012_owwaofficerprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='worker_type',
            field=models.CharField(choices=[('Land-based', 'Land-based OFW'), ('Sea-based', 'Sea-based OFW (Seafarer)'), ('Government-OFW', 'Government Employed OFW'), ('Business-OFW', 'Business / Entrepreneur OFW'), ('Student-OFW', 'Student / Scholar OFW'), ('Athlete-OFW', 'Athlete / Coach OFW'), ('Artist-OFW', 'Artist / Entertainer OFW'), ('Missionary-OFW', 'Missionary / Volunteer OFW'), ('Media-OFW', 'Media / Journalist OFW'), ('Dependent-OFW', 'Dependent Family Member'), ('Retiree-OFW', 'Retired OFW')], max_length=20),
        ),
    ]
