# Generated by Django 6.0 on 2026-05-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0013_alter_ofwregistration_worker_type'),
    ]

    operations = [
    ]
