# Generated by Django 6.0 on 2026-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0014_auto_20260523_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofwregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
