# Generated by Django 6.0 on 2026-05-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0015_alter_ofwregistration_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChangeHistory',
        ),
    ]
