# -*- coding: utf-8 -*-
# Generated by Django 6.0 on 2026-05-23 21:51
from django.db import migrations

def map_gender(sex):
    """Map sex from OFWFullProfile to gender choices in OFWRegistration."""
    if sex == 'F':
        return 'Female'
    elif sex == 'M':
        return 'Male'
    else:
        return 'Other'

def map_relationship(rel):
    """Map emergency_relationship to relationship choices in OFWRegistration."""
    # Normalize the string: capitalize first letter, lower rest
    rel_lower = rel.lower()
    if rel_lower == 'spouse':
        return 'Spouse'
    elif rel_lower == 'parent':
        return 'Parent'
    elif rel_lower == 'sibling':
        return 'Sibling'
    elif rel_lower == 'child':
        return 'Child'
    else:
        return 'Others'

def forwards_func(apps, schema_editor):
    """
    Migrate data from core_profiles_ofwfullprofile to core_profiles_ofwregistration.
    """
    OFWRegistration = apps.get_model('core_profiles', 'OFWRegistration')
    db_alias = schema_editor.connection.alias

    # Use raw SQL to fetch data from the ofwfullprofile table
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                client_id,
                first_name,
                middle_name,
                last_name,
                suffix,
                sex,
                date_of_birth,
                place_of_birth,
                civil_status,
                nationality,
                email,
                contact_number,
                present_address,
                province,
                city,
                postal_code,
                worker_type,
                country_of_deployment,
                occupation_position,
                recruitment_agency,
                date_of_deployment,
                expected_return,
                owwa_membership_status,
                owwa_membership_id,
                owwa_membership_date,
                owwa_expiry_date,
                emergency_contact_name,
                emergency_relationship,
                emergency_contact_number,
                created_at,
                updated_at,
                created_by_id,
                legacy_ofw_reg_id,
                updated_by_id
            FROM core_profiles_ofwfullprofile
        """)
        rows = cursor.fetchall()

    for row in rows:
        # Unpack the row
        (client_id, first_name, middle_name, last_name, suffix, sex, date_of_birth,
         place_of_birth, civil_status, nationality, email, contact_number,
         present_address, province, city, postal_code, worker_type,
         country_of_deployment, occupation_position, recruitment_agency,
         date_of_deployment, expected_return, owwa_membership_status,
         owwa_membership_id, owwa_membership_date, owwa_expiry_date,
         emergency_contact_name, emergency_relationship, emergency_contact_number,
         created_at, updated_at, created_by_id, legacy_ofw_reg_id, updated_by_id) = row

        # Map fields
        gender = map_gender(sex)
        relationship = map_relationship(emergency_relationship) if emergency_relationship else 'Others'

        # Create OFWRegistration instance
        OFWRegistration.objects.using(db_alias).create(
            client_id=client_id,
            first_name=first_name or "",
            last_name=last_name or "",
            birth_date=date_of_birth,
            gender=gender,
            civil_status=civil_status or "",
            nationality=nationality or "Filipino",
            phone_number=contact_number or "",
            email=email or "",
            address=present_address or "",
            worker_type=worker_type or "",
            country_of_deployment=country_of_deployment or "",
            occupation_position=occupation_position or "",
            recruitment_agency=recruitment_agency or "",
            contract_start=date_of_deployment,
            contract_end=expected_return,
            owwa_membership_status=owwa_membership_status or "",
            membership_number=owwa_membership_id or "",
            issue_date=owwa_membership_date,
            validity_date=owwa_expiry_date,
            emergency_contact_name=emergency_contact_name or "",
            relationship=relationship,
            emergency_contact_number=emergency_contact_number or "",
        )

def reverse_func(apps, schema_editor):
    """
    Reverse migration: Delete the OFWRegistration records that were created from OFWFullProfile.
    Note: This is not perfect if there were pre-existing records in OFWRegistration, but since
    we know the table was empty before, we can delete all.
    """
    OFWRegistration = apps.get_model('core_profiles', 'OFWRegistration')
    db_alias = schema_editor.connection.alias
    OFWRegistration.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core_profiles', '0016_remove_password_change_history'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]